### ISSUE TITLE
not able to compile with rust 1.81.0

### ISSUE THREAD

**Issue by geraldodev** [loco-rs/todo-list#7]
error[E0282]: type annotations needed for `Box<_>`
  --> /home/geraldo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.30/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
   = note: this is an inference error on crate `time` caused by an API change in Rust 1.80.0; update `time` to version `>=0.3.35` by calling `cargo update` 

rustc --version
rustc 1.81.0 (eeb90cda1 2024-09-04)

if I cargo update like the message says, it goes into another error.
error[E0046]: not all trait items implemented, missing: `boot`
  --> src/app.rs:18:1
   |
18 | impl Hooks for App {
   | ^^^^^^^^^^^^^^^^^^ missing `boot` in implementation
   |
   = help: implement the missing item: `fn boot(_: StartMode, _: &'life0 str) -> Pin<Box<(dyn Future<Output = std::result::Result<BootResult, loco_rs::Error>> + Send + 'async_trait)>> { todo!() }`

For more information about this error, try `rustc --explain E0046`.

Regards,

Geraldo Lopes de Souza

**Comment by daniel-dewa** [comment]
I've noticed the same issue.
